name: Run Documentation Script (for XSD files)
on:
  push:
    branches:
      - main
    paths:
      - '**.xsd'
jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Oxygen Documentation Script
        uses: oxygenxml/oxygen-script-documentation-action@v1.0.0
        env:
          SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
        with:
          schemaFile: schemas/main.xsd
